In [1]:
import pandas as pd
from mrmr import mrmr_classif
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn import datasets
%matplotlib inline
from sklearn import metrics
pd.set_option('display.max_columns', None)
from tqdm import tqdm
import time

from sklearn.linear_model import LogisticRegression , ridge_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, recall_score, accuracy_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn import datasets
%matplotlib inline
from sklearn import metrics

import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import pickle

In [2]:
df=pd.read_csv('player_stats.csv', sep=',', encoding='latin-1')

In [3]:
df.shape

(5682, 41)

In [4]:
df_after_drop = df.drop('marking', axis=1)

In [5]:
df_after_drop.shape

(5682, 40)

In [6]:
df_after_drop.columns

Index(['player', 'country', 'height', 'weight', 'age', 'club', 'ball_control',
       'dribbling', 'slide_tackle', 'stand_tackle', 'aggression', 'reactions',
       'att_position', 'interceptions', 'vision', 'composure', 'crossing',
       'short_pass', 'long_pass', 'acceleration', 'stamina', 'strength',
       'balance', 'sprint_speed', 'agility', 'jumping', 'heading',
       'shot_power', 'finishing', 'long_shots', 'curve', 'fk_acc', 'penalties',
       'volleys', 'gk_positioning', 'gk_diving', 'gk_handling', 'gk_kicking',
       'gk_reflexes', 'value'],
      dtype='object')

In [7]:
df_after_drop.head()

,player,country,height,weight,age,club,ball_control,dribbling,slide_tackle,stand_tackle,aggression,reactions,att_position,interceptions,vision,composure,crossing,short_pass,long_pass,acceleration,stamina,strength,balance,sprint_speed,agility,jumping,heading,shot_power,finishing,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes,value
0,Cristian Castro Devenish,Colombia,192,84,22,Atl. Nacional,55,43,68,73,72,68,30,65,30,50,33,64,49,41,55,86,40,52,43,51,64,54,30,31,32,34,41,33,10,11,6,7,9,$1.400.000
1,Silaldo Taffarel,Brazil,181,80,31,Corinthians,69,70,56,58,62,70,69,70,64,54,60,63,63,64,87,81,42,67,65,65,54,60,64,68,65,62,48,46,12,15,14,8,14,$975.00
2,Thomas DÃ¤hne,Germany,193,84,29,Holstein Kiel,25,12,13,16,27,65,17,20,49,48,14,35,18,46,38,68,41,48,36,60,17,51,14,20,20,15,26,16,64,74,65,68,74,$1.100.000
3,Michael Sollbauer,Austria,187,86,33,SK Rapid Wien,46,48,66,69,71,64,48,66,29,70,44,58,53,35,73,82,56,63,57,80,67,32,24,33,25,13,22,19,10,10,8,14,9,$650.00
4,Diego Segovia,Uruguay,191,80,23,Independiente,14,8,14,16,28,50,10,12,38,34,11,23,20,38,28,64,24,31,34,27,13,48,4,6,9,10,16,5,61,59,62,64,64,$300.00

In [8]:
df_after_drop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5682 entries, 0 to 5681
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player          5682 non-null   object
 1   country         5682 non-null   object
 2   height          5682 non-null   int64
 3   weight          5682 non-null   int64
 4   age             5682 non-null   int64
 5   club            5682 non-null   object
 6   ball_control    5682 non-null   int64
 7   dribbling       5682 non-null   int64
 8   slide_tackle    5682 non-null   int64
 9   stand_tackle    5682 non-null   int64
 10  aggression      5682 non-null   int64
 11  reactions       5682 non-null   int64
 12  att_position    5682 non-null   int64
 13  interceptions   5682 non-null   int64
 14  vision          5682 non-null   int64
 15  composure       5682 non-null   int64
 16  crossing        5682 non-null   int64
 17  short_pass      5682 non-null   int64
 18  long_pass       5682 non-null   int64
 19  acceleration    5682 non-null   int64
 20  stamina         5682 non-null   int64
 21  strength        5682 non-null   int64
 22  balance         5682 non-null   int64
 23  sprint_speed    5682 non-null   int64
 24  agility         5682 non-null   int64
 25  jumping         5682 non-null   int64
 26  heading         5682 non-null   int64
 27  shot_power      5682 non-null   int64
 28  finishing       5682 non-null   int64
 29  long_shots      5682 non-null   int64
 30  curve           5682 non-null   int64
 31  fk_acc          5682 non-null   int64
 32  penalties       5682 non-null   int64
 33  volleys         5682 non-null   int64
 34  gk_positioning  5682 non-null   int64
 35  gk_diving       5682 non-null   int64
 36  gk_handling     5682 non-null   int64
 37  gk_kicking      5682 non-null   int64
 38  gk_reflexes     5682 non-null   int64
 39  value           5682 non-null   object
dtypes: int64(36), object(4)
memory usage: 1.7+ MB

In [9]:
df_after_drop['player'].count()

5682

In [51]:
df_after_drop['value'] = df_after_drop['value'].str.replace('$', '').replace('.', '')
df_after_drop['value']= df_after_drop['value'].str.replace('.','')
df_after_drop

AttributeError: Can only use .str accessor with string values!

In [11]:
df_after_drop['value'] = df_after_drop['value'].apply(pd.to_numeric)

In [12]:
df_after_drop['value'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 5682 entries, 0 to 5681
Series name: value
Non-Null Count  Dtype
--------------  -----
5682 non-null   int64
dtypes: int64(1)
memory usage: 44.5 KB

In [13]:
df_after_drop.shape

(5682, 40)

In [14]:
df_after_drop_2 = df_after_drop.drop(['player', 'country', 'club'], axis = 1)

In [15]:
df_after_drop_2.shape

(5682, 37)

In [16]:
X = df_after_drop_2.drop(['value'], axis = 1)
y = df_after_drop_2['value']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 0)

In [18]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [19]:
y_pred = model.predict(X_test)
y_pred

array([  463209.35088738,  3274645.77050342,  2396801.9329615 , ...,
        7573489.86387816, -1449747.43241617,  1482398.83481024])

In [20]:
r2_score(y_test, y_pred)

0.3251481906620909

In [21]:
# run a linear to the dataset
model = LinearRegression()
model.fit(X_train, y_train)
y_pred_lin = model.predict(X_test)
print('Mean Squared Error :', mean_squared_error(y_test, y_pred_lin))
print('R2 score : ', r2_score(y_test, y_pred_lin))

Mean Squared Error : 27118626725124.285
R2 score :  0.3251481906620909

In [28]:
grouped = df_after_drop.groupby('player')['value'].sum().sort_values(ascending = False).reset_index()

In [32]:
grouped.head(60)

                    player      value
0            Kylian Mbappé  153500000
1           Kylian MbappÃ©  153500000
2           Erling Haaland  123000000
3          Kevin De Bruyne  107500000
4               Sadio Mané  101000000
5              Sadio ManÃ©  101000000
6                Neymar Jr   99500000
7            Mohamed Salah   99500000
8           Joshua Kimmich   97000000
9          Virgil van Dijk   84500000
10       Lautaro MartÃ­nez   79500000
11    Gianluigi Donnarumma   78000000
12          Marco Verratti   77500000
13       Federico Valverde   77500000
14                   Rodri   77000000
15         Bruno Fernandes   72500000
16           JoÃ£o Cancelo   72000000
17           Karim Benzema   64000000
18              Phil Foden   63500000
19        Martin Ãdegaard   62000000
20        Andrew Robertson   61500000
21                   Pedri   58500000
22                  Thiago   55500000
23           Romelu Lukaku   54000000
24            Lionel Messi   54000000
25           Gerard Moreno   53000000
26              Paul Pogba   52500000
27         Federico Chiesa   48500000
28            Rafael LeÃ£o   48500000
29             Bukayo Saka   47500000
30       Kalidou Koulibaly   46500000
31             Leroy SanÃ©   46000000
32       Antoine Griezmann   45500000
33        Domenico Berardi   45000000
34         RaphaÃ«l Varane   45000000
35            JoÃ£o FÃ©lix   43500000
36        Yannick Carrasco   42500000
37         Marcus Rashford   42000000
38                  Parejo   42000000
39             Mason Mount   42000000
40              Cody Gakpo   42000000
41  Franck Yannick KessiÃ©   41500000
42           Daichi Kamada   40500000
43               Oyarzabal   40500000
44                Jorginho   40500000
45           Ãngel Correa   39500000
46         Dayot Upamecano   36500000
47           Thomas Partey   36000000
48           Ferran Torres   36000000
49                  Antony   36000000
50           Tammy Abraham   35500000
51       Wissam Ben Yedder   35500000
52         Ronaldo Cabrais   35000000
53                 Canales   35000000
54       Rodrigo Bentancur   33500000
55              Marco Reus   33500000
56           Julian Brandt   33500000
57         RaÃºl de TomÃ¡s   33000000
58            JoÃ£o MÃ¡rio   31500000
59       Cristiano Ronaldo   31000000

In [33]:
# Ã© = é
# Ã£ = ã
# Ã = Á
# Ã = Ø
# Ãº = ú
# Ã¡ = á
#

In [34]:
#João Félix
#Ángel Correa
#Martin Ødegaard
#Raúl de Tomás

In [35]:
df_after_drop= df_after_drop.replace('[Ã©]', '', regex=True)

In [37]:
grouped = df_after_drop.groupby('player')['value'].sum().sort_values(ascending = False).reset_index()

In [38]:
grouped

                player      value
0        Kylian Mbappé  153500000
1         Kylian Mbapp  153500000
2       Erling Haaland  123000000
3      Kevin De Bruyne  107500000
4           Sadio Mané  101000000
...                ...        ...
5652  Thomas Mikkelsen       1500
5653  Eldin JakupoviÄ       1000
5654    Scott Flinders        600
5655     Andy Lonergan        600
5656     Richard Brush        400

[5657 rows x 2 columns]

In [48]:
df = pd.read_csv('player_stats.csv', sep=',' , encoding= "latin-1")

In [49]:
df

,player,country,height,weight,age,club,ball_control,dribbling,marking,slide_tackle,stand_tackle,aggression,reactions,att_position,interceptions,vision,composure,crossing,short_pass,long_pass,acceleration,stamina,strength,balance,sprint_speed,agility,jumping,heading,shot_power,finishing,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes,value
0,Cristian Castro Devenish,Colombia,192,84,22,Atl. Nacional,55,43,NaN,68,73,72,68,30,65,30,50,33,64,49,41,55,86,40,52,43,51,64,54,30,31,32,34,41,33,10,11,6,7,9,$1.400.000
1,Silaldo Taffarel,Brazil,181,80,31,Corinthians,69,70,NaN,56,58,62,70,69,70,64,54,60,63,63,64,87,81,42,67,65,65,54,60,64,68,65,62,48,46,12,15,14,8,14,$975.00
2,Thomas DÃ¤hne,Germany,193,84,29,Holstein Kiel,25,12,NaN,13,16,27,65,17,20,49,48,14,35,18,46,38,68,41,48,36,60,17,51,14,20,20,15,26,16,64,74,65,68,74,$1.100.000
3,Michael Sollbauer,Austria,187,86,33,SK Rapid Wien,46,48,NaN,66,69,71,64,48,66,29,70,44,58,53,35,73,82,56,63,57,80,67,32,24,33,25,13,22,19,10,10,8,14,9,$650.00
4,Diego Segovia,Uruguay,191,80,23,Independiente,14,8,NaN,14,16,28,50,10,12,38,34,11,23,20,38,28,64,24,31,34,27,13,48,4,6,9,10,16,5,61,59,62,64,64,$300.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5677,Mohamed Salah,Egypt,175,71,31,Liverpool,86,88,None,41,43,63,92,91,55,84,90,80,84,77,89,87,76,91,89,89,69,59,82,92,84,84,69,86,83,11,14,14,9,14,$99.500.000
5678,Sadio Mané,Senegal,174,69,31,FC Bayern München,86,88,None,38,42,75,91,90,35,84,84,78,84,71,91,85,72,88,86,93,87,84,83,85,78,77,64,75,75,7,10,10,15,14,$101.000.000
5679,Neymar Jr,Brazil,175,68,31,Paris SG,94,95,None,29,32,63,88,86,37,90,93,83,85,81,88,79,52,82,86,93,62,63,79,83,81,88,87,91,86,15,9,9,15,11,$99.500.000
5680,Cristiano Ronaldo,Portugal,187,83,38,Al Nassr,87,81,None,24,32,62,90,93,29,76,94,78,78,70,76,70,75,67,82,77,95,89,93,91,88,79,75,90,85,14,7,11,15,11,$31.000.000
5681,Zlatan Ibrahimovi?,Sweden,195,102,41,Milan,85,75,None,24,37,84,77,88,20,83,90,71,77,72,55,34,85,51,61,67,77,82,86,84,85,79,74,80,87,9,13,15,10,12,$10.500.000

In [50]:
df['country'].unique()

array(['Colombia', 'Brazil', 'Germany', 'Austria', 'Uruguay', 'Portugal',
       'Switzerland', 'Senegal', 'Mali', 'Saudi Arabia', 'Sweden',
       'India', 'England', 'Scotland', 'France', 'Korea Republic',
       'Italy', 'Norway', 'Turkey', 'Argentina', 'Republic of Ireland',
       'New Zealand', 'Poland', 'Ukraine', 'Chile', 'Romania',
       'Netherlands', 'Egypt', 'Spain', 'Denmark', 'Australia', 'Curacao',
       'Paraguay', 'Bolivia', 'Slovenia', 'Ecuador', 'Albania', 'Wales',
       'Morocco', 'China PR', 'Japan', 'Croatia', 'Peru', 'Ivory Coast',
       'South Africa', 'Ghana', 'Canada', 'Nigeria', 'Mauritius',
       'Iceland', 'Belgium', 'Jamaica', 'Zambia', 'Cape Verde',
       'United States', 'Northern Ireland', 'Indonesia',
       'United Arab Emirates', 'Greece', 'Burkina Faso',
       'Bosnia & Herzegovina', 'DR Congo', 'Guinea', 'Zimbabwe',
       'North Macedonia', 'Madagascar', 'Gabon', 'Hungary', 'Afghanistan',
       'Finland', 'Mexico', 'Guatemala', 'Sudan', 'Israel',
       'Guinea Bissau', 'Venezuela', 'Haiti', 'Armenia', 'Serbia',
       'Algeria', 'Iran', 'Slovakia', 'Tunisia', 'Mauritania',
       'Czech Republic', 'Montenegro', 'Kosovo', 'Central African Rep.',
       'Guyana', 'Philippines', 'Benin', 'Mozambique', 'Cameroon',
       'Cyprus', 'Antigua & Barbuda', 'St Kitts Nevis', 'Gambia',
       'Montserrat', 'Togo', 'Azerbaijan', 'Russia', 'El Salvador',
       'Lithuania', 'Luxembourg', 'Moldova', 'Congo', 'Suriname',
       'Costa Rica', 'Equatorial Guinea', 'Angola', 'Comoros',
       'Sierra Leone', 'Bulgaria', 'Korea DPR', 'Grenada', 'Libya',
       'Puerto Rico', 'Jordan', 'Malta', 'Estonia', 'Syria', 'Georgia',
       'Iraq', 'Cuba', 'Burundi', 'Liechtenstein', 'Uganda',
       'Trinidad & Tobago', 'Latvia', 'Seychelles', 'Honduras',
       'St Lucia', 'Kazakhstan', 'Gibraltar', 'Dominican Republic'],
      dtype=object)